//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.0.90
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;



namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Galeria</summary>
	[PublishedContentModel("galeria")]
	public partial class Galeria : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galeria";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Galeria(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Galeria, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Wydarzenia</summary>
	[PublishedContentModel("wydarzenia")]
	public partial class Wydarzenia : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "wydarzenia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Wydarzenia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Wydarzenia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Projekty</summary>
	[PublishedContentModel("projekty")]
	public partial class Projekty : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projekty";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Projekty(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Projekty, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Kontakt</summary>
	[PublishedContentModel("kontakt")]
	public partial class Kontakt : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "kontakt";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Kontakt(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Kontakt, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Aktualnosci</summary>
	[PublishedContentModel("aktualnosci")]
	public partial class Aktualnosci : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aktualnosci";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Aktualnosci(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Aktualnosci, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// AktualnosciDesc: Podpis pod tytułem strony
		///</summary>
		[ImplementPropertyType("aktualnosciDesc")]
		public IHtmlString AktualnosciDesc
		{
			get { return this.GetPropertyValue<IHtmlString>("aktualnosciDesc"); }
		}

		///<summary>
		/// AktualnosciHeader: Tytuł podstrony
		///</summary>
		[ImplementPropertyType("aktualnosciHeader")]
		public IHtmlString AktualnosciHeader
		{
			get { return this.GetPropertyValue<IHtmlString>("aktualnosciHeader"); }
		}
	}

	/// <summary>AktualnosciSzczegoly</summary>
	[PublishedContentModel("aktualnosciSzczegoly")]
	public partial class AktualnosciSzczegoly : Aktualnosci
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aktualnosciSzczegoly";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AktualnosciSzczegoly(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AktualnosciSzczegoly, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DateAndHour
		///</summary>
		[ImplementPropertyType("dateAndHour")]
		public DateTime DateAndHour
		{
			get { return this.GetPropertyValue<DateTime>("dateAndHour"); }
		}

		///<summary>
		/// EventFbLink: Link do wydarzenia na FB
		///</summary>
		[ImplementPropertyType("eventFbLink")]
		public string EventFbLink
		{
			get { return this.GetPropertyValue<string>("eventFbLink"); }
		}

		///<summary>
		/// EventRoom
		///</summary>
		[ImplementPropertyType("eventRoom")]
		public IHtmlString EventRoom
		{
			get { return this.GetPropertyValue<IHtmlString>("eventRoom"); }
		}

		///<summary>
		/// MainDesc
		///</summary>
		[ImplementPropertyType("mainDesc")]
		public IHtmlString MainDesc
		{
			get { return this.GetPropertyValue<IHtmlString>("mainDesc"); }
		}

		///<summary>
		/// MainTitle
		///</summary>
		[ImplementPropertyType("mainTitle")]
		public IHtmlString MainTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("mainTitle"); }
		}

		///<summary>
		/// newsIcon: Ikona dla danej aktualności
		///</summary>
		[ImplementPropertyType("newsIcon")]
		public object NewsIcon
		{
			get { return this.GetPropertyValue("newsIcon"); }
		}

		///<summary>
		/// ShortDesc: Opis wyświetlany na stronie głównej oraz na liście aktualności
		///</summary>
		[ImplementPropertyType("shortDesc")]
		public IHtmlString ShortDesc
		{
			get { return this.GetPropertyValue<IHtmlString>("shortDesc"); }
		}

		///<summary>
		/// ShortTitle: Tytuł wyświetlany na stronie głównej oraz na liście aktualności
		///</summary>
		[ImplementPropertyType("shortTitle")]
		public IHtmlString ShortTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("shortTitle"); }
		}

		///<summary>
		/// Speaker1Desc: Opis prelegenta
		///</summary>
		[ImplementPropertyType("speaker1Desc")]
		public IHtmlString Speaker1Desc
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker1Desc"); }
		}

		///<summary>
		/// Speaker1FbLink: Link do facebook'a prelegenta
		///</summary>
		[ImplementPropertyType("speaker1FbLink")]
		public string Speaker1FbLink
		{
			get { return this.GetPropertyValue<string>("speaker1FbLink"); }
		}

		///<summary>
		/// Speaker1Img: Zdjęcie prelegenta
		///</summary>
		[ImplementPropertyType("speaker1Img")]
		public object Speaker1Img
		{
			get { return this.GetPropertyValue("speaker1Img"); }
		}

		///<summary>
		/// Speaker1LinkedInLink: Link do LinkedIn prelegenta
		///</summary>
		[ImplementPropertyType("speaker1LinkedInLink")]
		public string Speaker1LinkedInLink
		{
			get { return this.GetPropertyValue<string>("speaker1LinkedInLink"); }
		}

		///<summary>
		/// Speaker1Name: Imię i Nazwisko prelegenta
		///</summary>
		[ImplementPropertyType("speaker1Name")]
		public IHtmlString Speaker1Name
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker1Name"); }
		}

		///<summary>
		/// Speaker1TwitterLink: Link do twittera prelegenta
		///</summary>
		[ImplementPropertyType("speaker1TwitterLink")]
		public string Speaker1TwitterLink
		{
			get { return this.GetPropertyValue<string>("speaker1TwitterLink"); }
		}

		///<summary>
		/// Speaker1WorkPosition: Stanowisko prelegenta
		///</summary>
		[ImplementPropertyType("speaker1WorkPosition")]
		public IHtmlString Speaker1WorkPosition
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker1WorkPosition"); }
		}

		///<summary>
		/// Speaker2Desc
		///</summary>
		[ImplementPropertyType("speaker2Desc")]
		public IHtmlString Speaker2Desc
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker2Desc"); }
		}

		///<summary>
		/// Speaker2FbLink
		///</summary>
		[ImplementPropertyType("speaker2FbLink")]
		public string Speaker2FbLink
		{
			get { return this.GetPropertyValue<string>("speaker2FbLink"); }
		}

		///<summary>
		/// Speaker2Img
		///</summary>
		[ImplementPropertyType("speaker2Img")]
		public object Speaker2Img
		{
			get { return this.GetPropertyValue("speaker2Img"); }
		}

		///<summary>
		/// Speaker2LinkedInLink
		///</summary>
		[ImplementPropertyType("speaker2LinkedInLink")]
		public string Speaker2LinkedInLink
		{
			get { return this.GetPropertyValue<string>("speaker2LinkedInLink"); }
		}

		///<summary>
		/// Speaker2Name
		///</summary>
		[ImplementPropertyType("speaker2Name")]
		public IHtmlString Speaker2Name
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker2Name"); }
		}

		///<summary>
		/// Speaker2TwitterLink
		///</summary>
		[ImplementPropertyType("speaker2TwitterLink")]
		public string Speaker2TwitterLink
		{
			get { return this.GetPropertyValue<string>("speaker2TwitterLink"); }
		}

		///<summary>
		/// Speaker2WorkPosition
		///</summary>
		[ImplementPropertyType("speaker2WorkPosition")]
		public IHtmlString Speaker2WorkPosition
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker2WorkPosition"); }
		}

		///<summary>
		/// Speaker3Desc
		///</summary>
		[ImplementPropertyType("speaker3Desc")]
		public IHtmlString Speaker3Desc
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker3Desc"); }
		}

		///<summary>
		/// Speaker3FbLink
		///</summary>
		[ImplementPropertyType("speaker3FbLink")]
		public string Speaker3FbLink
		{
			get { return this.GetPropertyValue<string>("speaker3FbLink"); }
		}

		///<summary>
		/// Speaker3Img
		///</summary>
		[ImplementPropertyType("speaker3Img")]
		public object Speaker3Img
		{
			get { return this.GetPropertyValue("speaker3Img"); }
		}

		///<summary>
		/// Speaker3LinkedInLink
		///</summary>
		[ImplementPropertyType("speaker3LinkedInLink")]
		public string Speaker3LinkedInLink
		{
			get { return this.GetPropertyValue<string>("speaker3LinkedInLink"); }
		}

		///<summary>
		/// Speaker3Name
		///</summary>
		[ImplementPropertyType("speaker3Name")]
		public IHtmlString Speaker3Name
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker3Name"); }
		}

		///<summary>
		/// Speaker3TwitterLink
		///</summary>
		[ImplementPropertyType("speaker3TwitterLink")]
		public string Speaker3TwitterLink
		{
			get { return this.GetPropertyValue<string>("speaker3TwitterLink"); }
		}

		///<summary>
		/// Speaker3WorkPosition
		///</summary>
		[ImplementPropertyType("speaker3WorkPosition")]
		public IHtmlString Speaker3WorkPosition
		{
			get { return this.GetPropertyValue<IHtmlString>("speaker3WorkPosition"); }
		}

		///<summary>
		/// TypeDropdown: Kategoria aktualności
		///</summary>
		[ImplementPropertyType("typeDropdown")]
		public object TypeDropdown
		{
			get { return this.GetPropertyValue("typeDropdown"); }
		}

		///<summary>
		/// YearDropdown: Rok dodania aktualności
		///</summary>
		[ImplementPropertyType("yearDropdown")]
		public object YearDropdown
		{
			get { return this.GetPropertyValue("yearDropdown"); }
		}
	}

	/// <summary>GaleriaSzczegoly</summary>
	[PublishedContentModel("galeriaSzczegoly")]
	public partial class GaleriaSzczegoly : Galeria
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galeriaSzczegoly";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GaleriaSzczegoly(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GaleriaSzczegoly, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ProjektySzczegoly</summary>
	[PublishedContentModel("projektySzczegoly")]
	public partial class ProjektySzczegoly : Projekty
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projektySzczegoly";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjektySzczegoly(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjektySzczegoly, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Layout</summary>
	[PublishedContentModel("layout")]
	public partial class Layout : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "layout";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Layout(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Layout, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// bannerSlideImage1
		///</summary>
		[ImplementPropertyType("bannerSlideImage1")]
		public object BannerSlideImage1
		{
			get { return this.GetPropertyValue("bannerSlideImage1"); }
		}

		///<summary>
		/// bannerSlideImage2
		///</summary>
		[ImplementPropertyType("bannerSlideImage2")]
		public object BannerSlideImage2
		{
			get { return this.GetPropertyValue("bannerSlideImage2"); }
		}

		///<summary>
		/// bannerSlideImage3
		///</summary>
		[ImplementPropertyType("bannerSlideImage3")]
		public object BannerSlideImage3
		{
			get { return this.GetPropertyValue("bannerSlideImage3"); }
		}

		///<summary>
		/// Banner text 1
		///</summary>
		[ImplementPropertyType("bannerText1")]
		public string BannerText1
		{
			get { return this.GetPropertyValue<string>("bannerText1"); }
		}

		///<summary>
		/// Banner text 1 inner
		///</summary>
		[ImplementPropertyType("bannerText1Inner")]
		public string BannerText1Inner
		{
			get { return this.GetPropertyValue<string>("bannerText1Inner"); }
		}

		///<summary>
		/// Banner text 2
		///</summary>
		[ImplementPropertyType("bannerText2")]
		public string BannerText2
		{
			get { return this.GetPropertyValue<string>("bannerText2"); }
		}

		///<summary>
		/// Banner text 2 inner
		///</summary>
		[ImplementPropertyType("bannerText2Inner")]
		public string BannerText2Inner
		{
			get { return this.GetPropertyValue<string>("bannerText2Inner"); }
		}

		///<summary>
		/// Banner text 3
		///</summary>
		[ImplementPropertyType("bannerText3")]
		public string BannerText3
		{
			get { return this.GetPropertyValue<string>("bannerText3"); }
		}

		///<summary>
		/// Banner text 3 inner
		///</summary>
		[ImplementPropertyType("bannerText3Inner")]
		public string BannerText3Inner
		{
			get { return this.GetPropertyValue<string>("bannerText3Inner"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public object UmbracoBytes
		{
			get { return this.GetPropertyValue("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public object UmbracoExtension
		{
			get { return this.GetPropertyValue("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public object UmbracoHeight
		{
			get { return this.GetPropertyValue("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public object UmbracoWidth
		{
			get { return this.GetPropertyValue("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public object UmbracoBytes
		{
			get { return this.GetPropertyValue("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public object UmbracoExtension
		{
			get { return this.GetPropertyValue("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Baner</summary>
	[PublishedContentModel("baner")]
	public partial class Baner : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Baner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Baner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public object UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public object UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public object UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public object UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public object UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public object UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
